export const GET_USER_BY_ID = "GET_USER_BY_ID";
export const RECEIVED_USER_BY_ID = "RECEIVED_USER_BY_ID";
export const PUSH_SCREEN = "PUSH_SCREEN";
export const POP_SCREEN = "POP_SCREEN";
export const GET_CARD_FEED_BATCH = "GET_CARD_FEED_BATCH";
export const RECEIVED_CARD_FEED_BATCH = "RECEIVED_CARD_FEED_BATCH";
export const GET_CARD_IMAGE_PATH = "GET_CARD_IMAGE_PATH";